module "linkerd" {
  providers = {
    kubectl = kubectl.main
    helm    = helm.main
  }

  source = "./linkerd"

  eks_oidc_provider_arn = module.eks.oidc_provider_arn
  region                = var.region
  nuon_id               = var.nuon_id
  tags                  = var.tags

  depends_on = [
    module.eks,
    resource.aws_security_group_rule.runner_cluster_access,
    module.nuon_dns[0].cert_manager,             // Certificate CRD
    module.nuon_dns[0].alb_ingress_controller,   // ALB webhook must be ready before creating Services
    kubectl_manifest.karpenter_nodepool_default, // We must first have nodes to run on
  ]
}

locals {
  // Keep this list aligned with the Linkerd resources generated by the shared
  // vendor policy in nuon-byoc/shared/policies/linkerd-authz-for-restate.shared.yml.
  linkerd_policy_crds = [
    "servers.policy.linkerd.io",
    "httproutes.policy.linkerd.io",
    "authorizationpolicies.policy.linkerd.io",
  ]
}

// Narrow bridge: depends only on the Linkerd CRD release, not the full module
// (control plane, PCA, certs). This avoids a destroy-time cycle while still
// letting the root module wait for policy CRDs to become discoverable before
// Kyverno starts validating generate rules that reference Linkerd GVRs.
resource "terraform_data" "linkerd_crds_ready" {
  input = module.linkerd.crds_ready
}

// Helm reporting success for linkerd-crds is not sufficient: the API server
// and already-running admission webhooks can lag before policy.linkerd.io is
// discoverable. Wait for both CRD establishment and discovery before starting
// Kyverno or applying vendor policies.
resource "terraform_data" "linkerd_policy_crds_discoverable" {
  triggers_replace = {
    cluster_ca_data  = module.eks.cluster_certificate_authority_data
    cluster_endpoint = module.eks.cluster_endpoint
    cluster_name     = local.cluster_name
    policy_crds      = join(",", local.linkerd_policy_crds)
    region           = var.region
  }

  lifecycle {
    replace_triggered_by = [terraform_data.linkerd_crds_ready]
  }

  provisioner "local-exec" {
    interpreter = ["/usr/bin/env", "bash", "-c"]
    command     = <<-EOT
      set -euo pipefail

      KUBECONFIG_FILE=$(mktemp)
      CA_FILE=$(mktemp)

      cleanup() {
        rm -f "$KUBECONFIG_FILE" "$CA_FILE"
      }

      trap cleanup EXIT

      if ! printf '%s' '${self.triggers_replace.cluster_ca_data}' | base64 --decode > "$CA_FILE" 2>/dev/null; then
        printf '%s' '${self.triggers_replace.cluster_ca_data}' | base64 -D > "$CA_FILE"
      fi

      cat > "$KUBECONFIG_FILE" <<EOF
apiVersion: v1
kind: Config
clusters:
- name: eks
  cluster:
    certificate-authority: $CA_FILE
    server: ${self.triggers_replace.cluster_endpoint}
contexts:
- name: eks
  context:
    cluster: eks
    user: eks
current-context: eks
users:
- name: eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - eks
      - get-token
      - --region
      - ${self.triggers_replace.region}
      - --cluster-name
      - ${self.triggers_replace.cluster_name}
EOF

      for crd in ${join(" ", local.linkerd_policy_crds)}; do
        echo "Waiting for CRD $crd to become Established..."
        kubectl --kubeconfig "$KUBECONFIG_FILE" wait --for=condition=Established --timeout=180s "crd/$crd"
      done

      echo "Waiting for Linkerd policy APIs to become discoverable..."
      for attempt in $(seq 1 36); do
        V1BETA3=$(kubectl --kubeconfig "$KUBECONFIG_FILE" get --raw /apis/policy.linkerd.io/v1beta3 2>/dev/null || true)
        V1ALPHA1=$(kubectl --kubeconfig "$KUBECONFIG_FILE" get --raw /apis/policy.linkerd.io/v1alpha1 2>/dev/null || true)

        if echo "$V1BETA3" | grep -q '"name":"servers"' \
          && echo "$V1BETA3" | grep -q '"name":"httproutes"' \
          && echo "$V1ALPHA1" | grep -q '"name":"authorizationpolicies"'; then
          echo "Linkerd policy APIs are discoverable."
          exit 0
        fi

        echo "Linkerd policy APIs not discoverable yet ($attempt/36); retrying in 5s..."
        sleep 5
      done

      echo "Timed out waiting for Linkerd policy APIs to become discoverable." >&2
      exit 1
    EOT
  }

  depends_on = [terraform_data.linkerd_crds_ready]
}
