---
name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  bump_tag:
    name: bump tag
    runs-on: ubuntu-latest
    steps:
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v
          release_branches: main
